title: "Diff-Symbo: Text-Controlled Long-Duration Symbolic Music Generation Using Latent Diffusion Model with Autoregressive Approach"
description: Submitted to AAAI 2025
show_downloads: False
google_analytics:
theme: jekyll-theme-slate
markdown: kramdown
